package GUI;

import org.w3c.dom.ls.LSOutput;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class registration_form {
    public static void main(String[] args) {
        registrationForm f = new registrationForm();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    }
}

class registrationForm extends JFrame implements ActionListener, ItemListener{

    JRadioButton r1,r2;
    JButton b;
    JTextField t1,t2;
    JLabel l,name, rollNo;
    JCheckBox c1,c2,c3,c4,c5;

    public registrationForm(){

        t1 = new JTextField(15);
        t2 = new JTextField(15);
        r1 = new JRadioButton("Male");
        r2 = new JRadioButton("Female");
        l = new JLabel("Greetings");
        name = new JLabel("name");
        rollNo = new JLabel("roll.no");
        b = new JButton("ok");
        c1 = new JCheckBox("Java");
        c2 = new JCheckBox("Python");
        c3 = new JCheckBox("DataBases");
        c4 = new JCheckBox("Kotlin");
        c5 = new JCheckBox("Dart");

        add(name);
        add(t1);
        add(rollNo);
        add(t2);

        ButtonGroup bg = new ButtonGroup();
        bg.add(r1);
        bg.add(r2);
        add(r1);
        add(r2);
        add(c1);
        add(c2);
        add(c3);
        add(c4);
        add(c5);
        add(b);
        add(l);

        c1.addItemListener((ItemListener) this);
        c2.addItemListener((ItemListener) this);
        c3.addItemListener((ItemListener) this);
        c4.addItemListener((ItemListener) this);
        c5.addItemListener((ItemListener) this);

        r1.addActionListener(this);
        r2.addActionListener(this);
        b.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String name = t1.getText();
                String rollNo = t2.getText();
                String language = " ";
                if(r1.isSelected()){
                    name = "Mr."+name;
                }
                else if(r2.isSelected() ){
                    name = "Ms."+name;
                }

                if(c1.isSelected()){
                    language = language + "Java ";
                }
                if(c2.isSelected())
                    language = language + "Python ";
                if(c3.isSelected())
                    language = language + "DataBases ";
                if(c4.isSelected())
                    language = language + "Kotlin ";
                if(c5.isSelected())
                    language = language + "Dart ";
                l.setText(name+" with roll.No "+ rollNo +" Selected Languages are "+ language);
            }
        });

        setTitle("Registration Form");

        setVisible(true);
        setSize(400,400);
        setLayout(new FlowLayout());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    @Override
    public void actionPerformed(ActionEvent e) {}

    public void itemStateChanged(ItemEvent e){}
}